export const legalMessageRows = `
Privacy Policy|Политика конфиденциальности|Գաղտնիության քաղաքականություն
Privacy Policy — YoYo|Политика конфиденциальности — YoYo|Գաղտնիության քաղաքականություն — YoYo
How YoYo collects, uses, and protects your data, including data from connected Instagram and TikTok accounts.|Как YoYo собирает, использует и защищает ваши данные, включая данные подключённых аккаунтов Instagram и TikTok.|Ինչպես է YoYo-ն հավաքում, օգտագործում և պաշտպանում ձեր տվյալները, ներառյալ կապակցված Instagram և TikTok հաշիվների տվյալները։
Last updated: September 2026|Последнее обновление: сентябрь 2026|Վերջին թարմացումը՝ սեպտեմբեր 2026
1. What this policy covers|1. Область действия политики|1. Քաղաքականության շրջանակը
This policy describes how YoYo ("the Service") collects, uses, stores, and shares information when you use our CRM and messaging platform, including when you connect a business Instagram or TikTok account.|Эта политика описывает, как YoYo («Сервис») собирает, использует, хранит и передаёт информацию при использовании нашей CRM и платформы обмена сообщениями, в том числе при подключении бизнес-аккаунта Instagram или TikTok.|Այս քաղաքականությունը նկարագրում է, թե ինչպես է YoYo-ն («Ծառայություն») հավաքում, օգտագործում, պահպանում և փոխանցում տեղեկությունները, երբ օգտվում եք մեր CRM և հաղորդագրությունների հարթակից, ներառյալ Instagram կամ TikTok բիզնես հաշիվ կապակցելիս։
2. Information we collect|2. Какие данные мы собираем|2. Մեր հավաքած տեղեկությունները
Account information:|Данные аккаунта:|Հաշվի տվյալներ՝
name, email address, and password (stored as a salted hash, never in plain text).|имя, адрес электронной почты и пароль (хранится в виде хеша с солью, никогда — в открытом виде).|անուն, էլ. փոստի հասցե և գաղտնաբառ (պահվում է աղով հեշի տեսքով, ոչ երբեք բաց տեքստով)։
Connected-platform data:|Данные подключённых платформ:|Կապակցված հարթակների տվյալներ՝
when you connect Instagram or TikTok, we receive the access tokens and permissions you grant, your connected account's profile info (username, display name, profile picture), and the customer conversations, messages, and comments that platform makes available through its API for the features you enable.|при подключении Instagram или TikTok мы получаем предоставленные вами токены доступа и разрешения, данные профиля (имя пользователя, отображаемое имя, фото), а также диалоги, сообщения и комментарии клиентов, доступные через API платформы для включённых вами функций.|Instagram կամ TikTok կապակցելիս մենք ստանում ենք ձեր տրամադրած մուտքի թոքեններն ու թույլտվությունները, հաշվի պրոֆիլի տվյալները (օգտանուն, ցուցադրվող անուն, նկար), ինչպես նաև հաճախորդների զրույցները, հաղորդագրություններն ու մեկնաբանությունները, որոնք հարթակի API-ն տրամադրում է ձեր միացրած գործառույթների համար։
Customer/lead data:|Данные клиентов и лидов:|Հաճախորդների և հնարավոր հաճախորդների տվյալներ՝
names, contact identifiers, message content, and CRM notes you or your team enter about your customers.|имена, контактные идентификаторы, содержание сообщений и заметки CRM, которые вы или ваша команда вносите о клиентах.|անուններ, կոնտակտային նույնացուցիչներ, հաղորդագրությունների բովանդակություն և CRM նշումներ, որոնք դուք կամ ձեր թիմը մուտքագրում եք հաճախորդների մասին։
Usage data:|Данные об использовании:|Օգտագործման տվյալներ՝
log data such as IP address, browser type, and pages visited, used for security and reliability.|данные журналов: IP-адрес, тип браузера и посещённые страницы — для безопасности и надёжности.|գրանցամատյանի տվյալներ՝ IP հասցե, դիտարկիչի տեսակ և այցելած էջեր, որոնք օգտագործվում են անվտանգության ու հուսալիության համար։
3. How we use this information|3. Как мы используем данные|3. Ինչպես ենք օգտագործում տեղեկությունները
To provide the core Service: displaying and letting you reply to conversations from your connected accounts, and organizing customer/lead records.|Для основных функций Сервиса: отображения диалогов подключённых аккаунтов и ответов на них, а также ведения записей о клиентах и лидах.|Ծառայության հիմնական գործառույթների համար՝ կապակցված հաշիվների զրույցների ցուցադրում և պատասխանելու հնարավորություն, հաճախորդների ու հնարավոր հաճախորդների գրառումների կազմակերպում։
To generate AI-assisted replies, where you have enabled that feature, by sending relevant conversation context to our AI provider.|Для подготовки ответов с помощью ИИ, если вы включили эту функцию, путём передачи соответствующего контекста диалога нашему поставщику ИИ.|ԱԲ-ի օգնությամբ պատասխաններ ստեղծելու համար, եթե միացրել եք այդ գործառույթը՝ զրույցի համապատասխան համատեքստը մեր ԱԲ մատակարարին ուղարկելով։
To maintain security, prevent abuse, and debug technical issues.|Для обеспечения безопасности, предотвращения злоупотреблений и устранения технических проблем.|Անվտանգությունը պահպանելու, չարաշահումները կանխելու և տեխնիկական խնդիրները շտկելու համար։
To communicate with you about your account or material changes to the Service.|Для связи с вами по вопросам аккаунта или существенных изменений Сервиса.|Ձեր հաշվի կամ Ծառայության էական փոփոխությունների վերաբերյալ ձեզ հետ կապվելու համար։
We do not sell your data or your customers' data, and we do not use data obtained from Instagram or TikTok for advertising purposes.|Мы не продаём ваши данные или данные ваших клиентов и не используем данные Instagram или TikTok в рекламных целях.|Մենք չենք վաճառում ձեր կամ ձեր հաճախորդների տվյալները և Instagram-ից կամ TikTok-ից ստացված տվյալները չենք օգտագործում գովազդային նպատակներով։
4. Sharing with third parties|4. Передача третьим лицам|4. Տվյալների փոխանցումը երրորդ կողմերին
We share data with the following categories of third parties, only as needed to run the Service:|Мы передаём данные следующим категориям третьих лиц только в объёме, необходимом для работы Сервиса:|Տվյալները փոխանցում ենք երրորդ կողմերի հետևյալ խմբերին՝ միայն Ծառայության աշխատանքի համար անհրաժեշտ չափով՝
and|и|և
— to send and receive messages/content through the accounts you connect, subject to their own platform terms.|— для отправки и получения сообщений и контента через подключённые аккаунты в соответствии с условиями этих платформ.|— կապակցված հաշիվներով հաղորդագրություններ և բովանդակություն ուղարկելու ու ստանալու համար՝ այդ հարթակների պայմաններին համապատասխան։
Our AI provider|Наш поставщик ИИ|Մեր ԱԲ մատակարարը
— to generate draft or automatic reply content, when that feature is enabled.|— для создания черновиков или автоматических ответов, если функция включена.|— պատասխանների սևագրեր կամ ավտոմատ պատասխաններ ստեղծելու համար, երբ այդ գործառույթը միացված է։
Infrastructure providers|Поставщики инфраструктуры|Ենթակառուցվածքի մատակարարները
— hosting, database, and file-storage providers that process data on our behalf under confidentiality obligations.|— поставщики хостинга, баз данных и файловых хранилищ, обрабатывающие данные от нашего имени с обязательствами конфиденциальности.|— հոսթինգի, տվյալների բազաների և ֆայլերի պահպանման մատակարարներ, որոնք մեր անունից մշակում են տվյալները՝ գաղտնիության պարտավորություններով։
5. Data retention|5. Хранение данных|5. Տվյալների պահպանումը
We retain account and conversation data for as long as your account is active, so that your conversation history and CRM records remain available to you. If you disconnect a platform account or close your account, we stop syncing new data from that platform and delete platform access tokens; you may request deletion of your remaining data at any time.|Мы храним данные аккаунта и диалогов, пока аккаунт активен, чтобы история общения и записи CRM оставались доступными. При отключении аккаунта платформы или закрытии вашего аккаунта мы прекращаем синхронизацию новых данных и удаляем токены доступа платформы. Вы можете в любое время запросить удаление оставшихся данных.|Հաշվի և զրույցների տվյալները պահպանում ենք այնքան ժամանակ, որքան հաշիվն ակտիվ է, որպեսզի զրույցների պատմությունն ու CRM գրառումները հասանելի մնան։ Հարթակի հաշիվն անջատելիս կամ ձեր հաշիվը փակելիս դադարեցնում ենք նոր տվյալների համաժամացումը և ջնջում հարթակի մուտքի թոքենները։ Մնացած տվյալների ջնջումը կարող եք պահանջել ցանկացած պահի։
6. Your rights|6. Ваши права|6. Ձեր իրավունքները
You may request access to, correction of, or deletion of your personal data by contacting the business operating this Service. If you are an individual whose data was collected as a customer/lead of one of our business users, please contact that business directly, as they control that data; we act as their data processor for conversation and CRM data.|Вы можете запросить доступ к своим персональным данным, их исправление или удаление, связавшись с компанией, управляющей Сервисом. Если ваши данные были собраны как данные клиента или лида одного из наших бизнес-пользователей, обратитесь напрямую в эту компанию: она управляет данными, а мы обрабатываем для неё данные диалогов и CRM.|Ձեր անձնական տվյալներին հասանելիություն, դրանց ուղղում կամ ջնջում կարող եք պահանջել՝ կապվելով Ծառայությունը շահագործող կազմակերպության հետ։ Եթե ձեր տվյալները հավաքվել են որպես մեր բիզնես օգտատերերից մեկի հաճախորդի տվյալներ, դիմեք անմիջապես այդ կազմակերպությանը․ այն վերահսկում է տվյալները, իսկ մենք մշակում ենք զրույցների և CRM տվյալները նրա անունից։
7. Security|7. Безопасность|7. Անվտանգությունը
Platform access tokens are stored encrypted at rest. Access to customer data is scoped per organization, and all traffic to the Service is encrypted in transit (HTTPS).|Токены доступа платформ хранятся в зашифрованном виде. Доступ к данным клиентов ограничен организацией, а весь трафик Сервиса шифруется при передаче (HTTPS).|Հարթակների մուտքի թոքենները պահվում են կոդավորված։ Հաճախորդների տվյալների հասանելիությունը սահմանափակված է կազմակերպությամբ, իսկ Ծառայության ամբողջ երթևեկությունը փոխանցման ընթացքում կոդավորված է (HTTPS)։
8. Changes to this policy|8. Изменения политики|8. Քաղաքականության փոփոխությունները
We may update this policy from time to time. Material changes will be reflected by updating the "Last updated" date above.|Мы можем периодически обновлять эту политику. Существенные изменения отражаются в дате «Последнее обновление» выше.|Ժամանակ առ ժամանակ կարող ենք թարմացնել այս քաղաքականությունը։ Էական փոփոխությունները կնշվեն վերևում նշված «Վերջին թարմացումը» ամսաթիվը փոխելով։
9. Contact|9. Контакты|9. Կապ
Questions about this policy can be sent to the business operating this Service.|Вопросы об этой политике можно направить компании, управляющей Сервисом.|Այս քաղաքականության վերաբերյալ հարցերը կարող եք ուղարկել Ծառայությունը շահագործող կազմակերպությանը։
Terms of Service|Условия использования|Օգտագործման պայմաններ
Terms of Service — YoYo|Условия использования — YoYo|Օգտագործման պայմաններ — YoYo
Terms of Service for the YoYo CRM and messaging platform.|Условия использования CRM и платформы обмена сообщениями YoYo.|YoYo CRM և հաղորդագրությունների հարթակի օգտագործման պայմանները։
1. Acceptance of terms|1. Принятие условий|1. Պայմանների ընդունումը
By creating an account or otherwise using YoYo ("the Service"), you agree to these Terms of Service. If you are using the Service on behalf of a business, you represent that you have the authority to bind that business to these terms.|Создавая аккаунт или иным образом используя YoYo («Сервис»), вы принимаете эти Условия использования. Если вы действуете от имени компании, вы подтверждаете полномочия принять эти условия от её имени.|Ստեղծելով հաշիվ կամ այլ կերպ օգտագործելով YoYo-ն («Ծառայություն»)՝ դուք համաձայնում եք այս պայմաններին։ Եթե օգտվում եք կազմակերպության անունից, հաստատում եք, որ իրավասու եք նրա անունից ընդունելու այս պայմանները։
2. What the Service does|2. Что делает Сервис|2. Ծառայության գործառույթները
YoYo is a CRM and customer-messaging platform for small and mid-sized businesses. It lets you connect business accounts on third-party platforms (currently Instagram and TikTok), view and reply to customer conversations from those platforms in one place, optionally use AI-generated draft or automatic replies, and track leads through a sales pipeline.|YoYo — CRM и платформа общения с клиентами для малого и среднего бизнеса. Она позволяет подключать бизнес-аккаунты сторонних платформ (сейчас Instagram и TikTok), просматривать диалоги и отвечать в одном месте, по желанию использовать черновики или автоматические ответы ИИ и отслеживать лиды в воронке продаж.|YoYo-ն CRM և հաճախորդների հետ հաղորդակցման հարթակ է փոքր ու միջին բիզնեսների համար։ Այն թույլ է տալիս կապակցել երրորդ կողմերի բիզնես հաշիվները (ներկայում՝ Instagram և TikTok), մեկ տեղում դիտել ու պատասխանել զրույցներին, ցանկության դեպքում օգտագործել ԱԲ-ի ստեղծած սևագրեր կամ ավտոմատ պատասխաններ և հետևել հնարավոր հաճախորդներին վաճառքի փուլերում։
3. Your account and connected platforms|3. Аккаунт и подключённые платформы|3. Ձեր հաշիվն ու կապակցված հարթակները
You are responsible for the accuracy of the information in your account and for maintaining the confidentiality of your login credentials. When you connect an Instagram or TikTok account, you authorize YoYo to access and act on that account within the scope of the permissions you grant, and you remain responsible for complying with that platform's own terms of service and platform policies.|Вы отвечаете за точность данных аккаунта и конфиденциальность данных для входа. Подключая Instagram или TikTok, вы разрешаете YoYo доступ и действия в пределах предоставленных разрешений и обязуетесь соблюдать условия и политики соответствующей платформы.|Դուք պատասխանատու եք հաշվի տեղեկությունների ճշտության և մուտքի տվյալների գաղտնիության համար։ Instagram կամ TikTok հաշիվ կապակցելով՝ լիազորում եք YoYo-ին հասանելիություն ունենալ և գործել ձեր տրամադրած թույլտվությունների շրջանակում՝ շարունակելով պատասխանատու լինել հարթակի պայմանների ու քաղաքականությունների պահպանման համար։
4. Acceptable use|4. Допустимое использование|4. Թույլատրելի օգտագործումը
You agree not to use the Service to:|Вы соглашаетесь не использовать Сервис для:|Դուք համաձայնում եք Ծառայությունը չօգտագործել հետևյալի համար՝
Send unsolicited bulk messages (spam) or otherwise violate a connected platform's messaging policies;|Отправки нежелательных массовых сообщений (спама) или нарушения правил обмена сообщениями подключённой платформы;|Չպահանջված զանգվածային հաղորդագրությունների (սպամի) ուղարկում կամ կապակցված հարթակի հաղորդագրությունների կանոնների այլ խախտում,
Upload or transmit unlawful, infringing, or harmful content;|Загрузки или передачи незаконного, нарушающего права или вредоносного контента;|Անօրինական, իրավունքներ խախտող կամ վնասակար բովանդակության բեռնում կամ փոխանցում,
Attempt to gain unauthorized access to other users' data or to the Service's infrastructure;|Попыток несанкционированного доступа к данным других пользователей или инфраструктуре Сервиса;|Այլ օգտատերերի տվյալներին կամ Ծառայության ենթակառուցվածքին չարտոնված հասանելիության փորձեր,
Use the Service in a way that violates any applicable law or the terms of a connected third-party platform.|Использования Сервиса с нарушением применимого закона или условий подключённой сторонней платформы.|Ծառայության օգտագործում՝ կիրառելի օրենքը կամ կապակցված երրորդ կողմի հարթակի պայմանները խախտելով։
5. AI-generated content|5. Контент, созданный ИИ|5. ԱԲ-ի ստեղծած բովանդակությունը
When enabled, the Service uses a third-party AI provider to draft or send replies to your customers on your behalf, based on information you provide about your business. You are responsible for reviewing how this feature is configured for your account and for the content it sends where you have enabled automatic sending.|Если функция включена, Сервис использует стороннего поставщика ИИ для подготовки или отправки ответов клиентам от вашего имени на основе предоставленной информации о бизнесе. Вы отвечаете за проверку настроек функции и за отправляемый контент, если включили автоматическую отправку.|Երբ գործառույթը միացված է, Ծառայությունն օգտագործում է երրորդ կողմի ԱԲ մատակարար՝ ձեր բիզնեսի մասին տրամադրած տեղեկությունների հիման վրա ձեր անունից պատասխաններ պատրաստելու կամ ուղարկելու համար։ Դուք պատասխանատու եք գործառույթի կարգավորումները ստուգելու և ավտոմատ ուղարկումը միացնելու դեպքում՝ ուղարկվող բովանդակության համար։
6. Data and content ownership|6. Права на данные и контент|6. Տվյալների և բովանդակության սեփականությունը
You retain ownership of the business data, customer data, and content you submit to the Service. You grant YoYo a limited license to process that data solely to provide and improve the Service, as described in our|Вы сохраняете права на данные бизнеса, клиентов и переданный контент. Вы предоставляете YoYo ограниченную лицензию на обработку этих данных исключительно для предоставления и улучшения Сервиса, как описано в документе|Դուք պահպանում եք Ծառայությանը տրամադրած բիզնեսի տվյալների, հաճախորդների տվյալների և բովանդակության սեփականությունը։ YoYo-ին տրամադրում եք այդ տվյալների մշակման սահմանափակ իրավունք՝ միայն Ծառայությունը տրամադրելու և բարելավելու նպատակով, ինչպես նկարագրված է փաստաթղթում՝
7. Termination|7. Прекращение использования|7. Օգտագործման դադարեցումը
You may stop using the Service and disconnect any connected accounts at any time. We may suspend or terminate access to the Service for accounts that violate these terms or that we reasonably believe pose a security or legal risk.|Вы можете в любое время прекратить использование Сервиса и отключить подключённые аккаунты. Мы можем приостановить или прекратить доступ аккаунтов, нарушающих эти условия или, по нашему обоснованному мнению, создающих угрозы безопасности или правовые риски.|Կարող եք ցանկացած պահի դադարեցնել Ծառայության օգտագործումն ու անջատել կապակցված հաշիվները։ Մենք կարող ենք կասեցնել կամ դադարեցնել այն հաշիվների հասանելիությունը, որոնք խախտում են պայմանները կամ, մեր հիմնավորված կարծիքով, առաջացնում են անվտանգության կամ իրավական ռիսկեր։
8. Disclaimers and limitation of liability|8. Отказ от гарантий и ограничение ответственности|8. Երաշխիքների բացառում և պատասխանատվության սահմանափակում
The Service is provided "as is" without warranties of any kind. To the maximum extent permitted by law, YoYo is not liable for indirect, incidental, or consequential damages arising from your use of the Service, including damages arising from actions taken by a connected third-party platform outside our control.|Сервис предоставляется «как есть», без каких-либо гарантий. В максимально допустимой законом степени YoYo не несёт ответственности за косвенные, случайные или последующие убытки от использования Сервиса, включая ущерб от неподконтрольных нам действий подключённых сторонних платформ.|Ծառայությունը տրամադրվում է «ինչպես կա»՝ առանց որևէ երաշխիքի։ Օրենքով թույլատրելի առավելագույն չափով YoYo-ն պատասխանատու չէ Ծառայության օգտագործումից առաջացած անուղղակի, պատահական կամ հետևանքային վնասների համար, ներառյալ մեր վերահսկողությունից դուրս կապակցված երրորդ կողմի հարթակների գործողություններից առաջացած վնասները։
9. Changes to these terms|9. Изменение условий|9. Պայմանների փոփոխությունները
We may update these terms from time to time. Continued use of the Service after an update constitutes acceptance of the revised terms.|Мы можем периодически обновлять эти условия. Продолжая пользоваться Сервисом после обновления, вы принимаете изменённые условия.|Ժամանակ առ ժամանակ կարող ենք թարմացնել այս պայմանները։ Թարմացումից հետո Ծառայության շարունակական օգտագործումը նշանակում է վերանայված պայմանների ընդունում։
10. Contact|10. Контакты|10. Կապ
Questions about these terms can be sent to the business operating this Service.|Вопросы об этих условиях можно направить компании, управляющей Сервисом.|Այս պայմանների վերաբերյալ հարցերը կարող եք ուղարկել Ծառայությունը շահագործող կազմակերպությանը։
`.trim().split("\n").map((row) => row.split("|") as [string, string, string]);
